export enum UserRole {
  ELEVE = 'ELEVE',
  PARENT = 'PARENT',
  ENSEIGNANT = 'ENSEIGNANT',
  CENSEUR = 'CENSEUR',
  PROVISEUR = 'PROVISEUR',
  INSPECTEUR = 'INSPECTEUR',
  ADMIN_MENETFP = 'ADMIN_MENETFP',
}
